version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion-stock-backend
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://gestion-stock-mongodb:27017/product_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.20
    container_name: gestion-stock-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=product_db

volumes:
  mongodb_data:
