name: Construire et publier l'image Docker

on : 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Récupère le code du dépôt

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'  # Version Java à utiliser

      - name: Build with Maven
        run: mvn clean package


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "ismatou"
        password: "dckr_pat_nQrgsqWl7MfP6O4-nvPfm8LGn40"

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Vérifie l'installation de Docker Compose

    #- name: Build and start with docker compose
      #run: |
        #docker-compose up --build
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ismatou/Gestion-stock-management:Gestion-stock-management_backend_v1

